// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGyxfZ2c2xySDSIlUlNvpMPO-zp5K5jKM',
    appId: '1:611925015953:web:6a790179af8c8a6c62ee30',
    messagingSenderId: '611925015953',
    projectId: 'lembretes-1a2b9',
    authDomain: 'lembretes-1a2b9.firebaseapp.com',
    storageBucket: 'lembretes-1a2b9.appspot.com',
    measurementId: 'G-EKZ2DRSRGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqbOgN_FYERE_Suo0OFbo1B2TZwxO9BQ4',
    appId: '1:611925015953:android:3711d4c4ff1d8dca62ee30',
    messagingSenderId: '611925015953',
    projectId: 'lembretes-1a2b9',
    storageBucket: 'lembretes-1a2b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTvtaBK6kKb20jrqRYb48GvwXlysPhmY0',
    appId: '1:611925015953:ios:9303e4f01d221a0d62ee30',
    messagingSenderId: '611925015953',
    projectId: 'lembretes-1a2b9',
    storageBucket: 'lembretes-1a2b9.appspot.com',
    iosBundleId: 'com.lembrancas.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTvtaBK6kKb20jrqRYb48GvwXlysPhmY0',
    appId: '1:611925015953:ios:9303e4f01d221a0d62ee30',
    messagingSenderId: '611925015953',
    projectId: 'lembretes-1a2b9',
    storageBucket: 'lembretes-1a2b9.appspot.com',
    iosBundleId: 'com.lembrancas.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGyxfZ2c2xySDSIlUlNvpMPO-zp5K5jKM',
    appId: '1:611925015953:web:156b06f0ee18d97c62ee30',
    messagingSenderId: '611925015953',
    projectId: 'lembretes-1a2b9',
    authDomain: 'lembretes-1a2b9.firebaseapp.com',
    storageBucket: 'lembretes-1a2b9.appspot.com',
    measurementId: 'G-TEMDWDH8RJ',
  );
}
